openapi: "3.0.2"
info:
  title: API Authentication
  version: "1.0"
servers:
  - url: https://localhost:8080
tags:
  - name: Authentication

paths:
  /authentication/api/v1/auth/token:
    post:
      tags:
        - Authentication
      summary: Authenticate to the application and get back the token in the response
      operationId: authenticateForToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'

  /authentication/api/v1/auth/cookie:
    post:
      tags:
        - Authentication
      summary: Authenticate to the application and get back the token in a cookie
      operationId: authenticateForCookie
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'

      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/BaseResponse'

components:
  schemas:
    BaseResponse:
      type: object
      description: Base response
      properties:
        status:
          type: string

    AuthenticationRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    AuthenticationResponse:
      type: object
      properties:
        token:
          type: string