spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgresDB}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:passw0rd}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true